/**
 * Graph Database Component
 * Creates the graph structure for UTech campus navigation with weighted edges
 * 
 * Graph Node Structure:
 * - name: string
 * - type: 'building' or 'walkway'
 * - neighbors: g_node[]
 * - x_coor: number (pixel coordinate)
 * - y_coor: number (pixel coordinate)
 * 
 * Edge weights are calculated as Euclidean distance between nodes
 * 
 * Map Feature Classification:
 * A. Walkways (type='walkway'): Straight segments, Curves, Intersections, Roundabouts
 * B. Buildings (type='building'): Building entrance nodes
 * C. Gates (type='building'): Main gate, Walkin gate, Back gate
 */

class GraphNode {
    constructor(name, type, x_coor, y_coor) {
        this.name = name;
        this.type = type; // 'building' or 'walkway'
        this.neighbors = [];
        this.x_coor = x_coor;
        this.y_coor = y_coor;
    }

    addNeighbor(node) {
        if (!this.neighbors.includes(node)) {
            this.neighbors.push(node);
        }
    }

    addBidirectionalNeighbor(node) {
        this.addNeighbor(node);
        node.addNeighbor(this);
    }
}

class GraphDatabase {
    constructor() {
        this.buildingGraph = new Map();
        this.buildGraph();
    }

    buildGraph() {
        // Created Nodes
        const south_g4 = new GraphNode('south_g4', 'gate', 1283, 3117);
        const east_g5 = new GraphNode('east_g5', 'gate', 1721, 3185);
        const east_g6 = new GraphNode('east_g6', 'gate', 2135, 30);
        const east_b3 = new GraphNode('east_b3', 'building', 1443, 2220);
        const east_b4 = new GraphNode('east_b4', 'building', 1811, 1911);
        const east_b6 = new GraphNode('east_b6', 'building', 1578, 1777);
        const central_b7 = new GraphNode('central_b7', 'building', 1357, 1597);
        const north_b9 = new GraphNode('north_b9', 'building', 1273, 1053);
        const west_b11 = new GraphNode('west_b11', 'building', 674, 1644);
        const west_b12 = new GraphNode('west_b12', 'building', 694, 1386);
        const central_b13 = new GraphNode('central_b13', 'building', 1084, 2132);
        const central_b14 = new GraphNode('central_b14', 'building', 1277, 1972);
        const central_b15 = new GraphNode('central_b15', 'building', 1264, 1861);
        const west_b16 = new GraphNode('west_b16', 'building', 266, 2905);
        const south_w1 = new GraphNode('south_w1', 'walkway', 1324, 2918);
        const south_w2 = new GraphNode('south_w2', 'walkway', 1346, 2713);
        const south_w4 = new GraphNode('south_w4', 'walkway', 1170, 2465);
        const central_w5 = new GraphNode('central_w5', 'walkway', 1275, 2231);
        const central_w6 = new GraphNode('central_w6', 'walkway', 1175, 2232);
        const east_w7 = new GraphNode('east_w7', 'walkway', 1460, 2490);
        const east_w8 = new GraphNode('east_w8', 'walkway', 1608, 2437);
        const east_w9 = new GraphNode('east_w9', 'walkway', 1712, 2435);
        const east_w10 = new GraphNode('east_w10', 'walkway', 1739, 2504);
        const south_w11 = new GraphNode('south_w11', 'walkway', 1411, 2938);
        const east_w12 = new GraphNode('east_w12', 'walkway', 1603, 3026);
        const east_w13 = new GraphNode('east_w13', 'walkway', 1725, 3055);
        const east_w14 = new GraphNode('east_w14', 'walkway', 1775, 3013);
        const east_w15 = new GraphNode('east_w15', 'walkway', 1795, 2753);
        const east_w16 = new GraphNode('east_w16', 'walkway', 1759, 2612);
        const east_w17 = new GraphNode('east_w17', 'walkway', 1796, 2587);
        const east_w18 = new GraphNode('east_w18', 'walkway', 1888, 2708);
        const east_w19 = new GraphNode('east_w19', 'walkway', 1896, 2771);
        const east_w20 = new GraphNode('east_w20', 'walkway', 1872, 3026);
        const east_w21 = new GraphNode('east_w21', 'walkway', 1860, 3094);
        const east_w22 = new GraphNode('east_w22', 'walkway', 1726, 2231);
        const east_w23 = new GraphNode('east_w23', 'walkway', 1552, 2225);
        const east_w24 = new GraphNode('east_w24', 'walkway', 1731, 2187);
        const east_w25 = new GraphNode('east_w25', 'walkway', 1720, 2027);
        const east_w26 = new GraphNode('east_w26', 'walkway', 1667, 2010);
        const east_w27 = new GraphNode('east_w27', 'walkway', 1669, 1914);
        const east_w28 = new GraphNode('east_w28', 'walkway', 1676, 1721);
        const east_w29 = new GraphNode('east_w29', 'walkway', 1663, 1611);
        const east_w30 = new GraphNode('east_w30', 'walkway', 1576, 1605);
        const east_w31 = new GraphNode('east_w31', 'walkway', 1574, 1680);
        const east_w32 = new GraphNode('east_w32', 'walkway', 1732, 1607);
        const east_w33 = new GraphNode('east_w33', 'walkway', 1711, 1466);
        const central_w35 = new GraphNode('central_w35', 'walkway', 1286, 1528);
        const central_w36 = new GraphNode('central_w36', 'walkway', 1142, 1572);
        const east_w37 = new GraphNode('east_w37', 'walkway', 1666, 1216);
        const east_w38 = new GraphNode('east_w38', 'walkway', 1545, 1125);
        const north_w39 = new GraphNode('north_w39', 'walkway', 1287, 1168);
        const north_w40 = new GraphNode('north_w40', 'walkway', 1079, 1187);
        const east_w41 = new GraphNode('east_w41', 'walkway', 2112, 106);
        const east_w42 = new GraphNode('east_w42', 'walkway', 2075, 270);
        const east_w43 = new GraphNode('east_w43', 'walkway', 2068, 516);
        const east_w44 = new GraphNode('east_w44', 'walkway', 2028, 572);
        const east_w45 = new GraphNode('east_w45', 'walkway', 1658, 621);
        const east_w46 = new GraphNode('east_w46', 'walkway', 1609, 638);
        const east_w47 = new GraphNode('east_w47', 'walkway', 1555, 884);
        const north_w48 = new GraphNode('north_w48', 'walkway', 1209, 696);
        const north_w49 = new GraphNode('north_w49', 'walkway', 1173, 578);
        const central_w50 = new GraphNode('central_w50', 'walkway', 846, 1200);
        const north_w51 = new GraphNode('north_w51', 'walkway', 803, 948);
        const west_w52 = new GraphNode('west_w52', 'walkway', 458, 980);
        const north_w53 = new GraphNode('north_w53', 'walkway', 999, 871);
        const north_w54 = new GraphNode('north_w54', 'walkway', 989, 711);
        const north_w55 = new GraphNode('north_w55', 'walkway', 801, 730);
        const north_w56 = new GraphNode('north_w56', 'walkway', 759, 433);
        const north_w57 = new GraphNode('north_w57', 'walkway', 1135, 362);
        const west_w58 = new GraphNode('west_w58', 'walkway', 659, 952);
        const west_w59 = new GraphNode('west_w59', 'walkway', 395, 845);
        const west_w60 = new GraphNode('west_w60', 'walkway', 440, 837);
        const west_w61 = new GraphNode('west_w61', 'walkway', 367, 784);
        const west_w62 = new GraphNode('west_w62', 'walkway', 157, 996);
        const west_w63 = new GraphNode('west_w63', 'walkway', 453, 1002);
        const west_w64 = new GraphNode('west_w64', 'walkway', 502, 1430);
        const west_w65 = new GraphNode('west_w65', 'walkway', 523, 1468);
        const west_w66 = new GraphNode('west_w66', 'walkway', 595, 1331);
        const central_w67 = new GraphNode('central_w67', 'walkway', 720, 1239);
        const west_w68 = new GraphNode('west_w68', 'walkway', 515, 1507);
        const west_w69 = new GraphNode('west_w69', 'walkway', 161, 1495);
        const west_w70 = new GraphNode('west_w70', 'walkway', 512, 1628);
        const west_w71 = new GraphNode('west_w71', 'walkway', 490, 1887);
        const central_w72 = new GraphNode('central_w72', 'walkway', 787, 1929);
        const central_w73 = new GraphNode('central_w73', 'walkway', 887, 1926);
        const central_w74 = new GraphNode('central_w74', 'walkway', 898, 1749);
        const central_w75 = new GraphNode('central_w75', 'walkway', 888, 1673);
        const central_w76 = new GraphNode('central_w76', 'walkway', 882, 1605);
        const central_w77 = new GraphNode('central_w77', 'walkway', 986, 1603);
        const central_w78 = new GraphNode('central_w78', 'walkway', 986, 1668);
        const central_w79 = new GraphNode('central_w79', 'walkway', 1010, 1632);
        const central_w80 = new GraphNode('central_w80', 'walkway', 1122, 1600);
        const central_w81 = new GraphNode('central_w81', 'walkway', 1123, 1640);
        const central_w82 = new GraphNode('central_w82', 'walkway', 1089, 1710);
        const central_w83 = new GraphNode('central_w83', 'walkway', 1079, 1792);
        const central_w84 = new GraphNode('central_w84', 'walkway', 1096, 1868);
        const central_w85 = new GraphNode('central_w85', 'walkway', 1127, 1931);
        const central_w86 = new GraphNode('central_w86', 'walkway', 1112, 1971);
        const central_w88 = new GraphNode('central_w88', 'walkway', 894, 2063);
        const central_w89 = new GraphNode('central_w89', 'walkway', 769, 2046);
        const central_w90 = new GraphNode('central_w90', 'walkway', 735, 2179);
        const west_w91 = new GraphNode('west_w91', 'walkway', 697, 2298);
        const west_w92 = new GraphNode('west_w92', 'walkway', 678, 2355);
        const central_w93 = new GraphNode('central_w93', 'walkway', 855, 2080);
        const central_w94 = new GraphNode('central_w94', 'walkway', 823, 2174);
        const central_w96 = new GraphNode('central_w96', 'walkway', 802, 2237);
        const central_w97 = new GraphNode('central_w97', 'walkway', 861, 2252);
        const central_w98 = new GraphNode('central_w98', 'walkway', 762, 2370);
        const central_w99 = new GraphNode('central_w99', 'walkway', 834, 2380);
        const west_w100 = new GraphNode('west_w100', 'walkway', 552, 2336);
        const west_w101 = new GraphNode('west_w101', 'walkway', 475, 2284);
        const west_w102 = new GraphNode('west_w102', 'walkway', 469, 2150);
        const west_w103 = new GraphNode('west_w103', 'walkway', 469, 2000);
        const south_w104 = new GraphNode('south_w104', 'walkway', 721, 2486);
        const west_w105 = new GraphNode('west_w105', 'walkway', 683, 2615);
        const west_w106 = new GraphNode('west_w106', 'walkway', 634, 2685);
        const west_w107 = new GraphNode('west_w107', 'walkway', 619, 2771);
        const west_w108 = new GraphNode('west_w108', 'walkway', 590, 2853);
        const west_w109 = new GraphNode('west_w109', 'walkway', 504, 2880);
        const west_w110 = new GraphNode('west_w110', 'walkway', 111, 2839);
        const west_w111 = new GraphNode('west_w111', 'walkway', 102, 3099);
        const west_w112 = new GraphNode('west_w112', 'walkway', 426, 3120);
        const west_w113 = new GraphNode('west_w113', 'walkway', 270, 2853);
        const west_w114 = new GraphNode('west_w114', 'walkway', 513, 1754);
        const west_w115 = new GraphNode('west_w115', 'walkway', 477, 1212);
        const central_w116 = new GraphNode('central_w116', 'walkway', 1317, 2159);
        const central_w117 = new GraphNode('central_w117', 'walkway', 1331, 2007);
        const central_w118 = new GraphNode('central_w118', 'walkway', 1418, 2077);
        const central_w119 = new GraphNode('central_w119', 'walkway', 1333, 1929);
        const central_w120 = new GraphNode('central_w120', 'walkway', 1358, 1882);
        const east_w121 = new GraphNode('east_w121', 'walkway', 1484, 1781);
        const east_w122 = new GraphNode('east_w122', 'walkway', 1516, 1742);
        const central_w123 = new GraphNode('central_w123', 'walkway', 1356, 1768);
        const central_w124 = new GraphNode('central_w124', 'walkway', 1354, 1647);
        const central_w126 = new GraphNode('central_w126', 'walkway', 1380, 1510);
        const central_w127 = new GraphNode('central_w127', 'walkway', 1356, 1486);
        const central_w128 = new GraphNode('central_w128', 'walkway', 1377, 1417);
        const central_w129 = new GraphNode('central_w129', 'walkway', 1387, 1356);
        const central_w130 = new GraphNode('central_w130', 'walkway', 1427, 1297);
        const east_w131 = new GraphNode('east_w131', 'walkway', 1549, 1489);
        const east_w132 = new GraphNode('east_w132', 'walkway', 1513, 1443);
        const east_w133 = new GraphNode('east_w133', 'walkway', 1473, 1388);
        const central_w134 = new GraphNode('central_w134', 'walkway', 1342, 1339);
        const central_w135 = new GraphNode('central_w135', 'walkway', 1284, 1351);
        const central_w136 = new GraphNode('central_w136', 'walkway', 1291, 1259);
        const central_w137 = new GraphNode('central_w137', 'walkway', 1252, 1335);
        const central_w139 = new GraphNode('central_w139', 'walkway', 1102, 1362);
        const central_w140 = new GraphNode('central_w140', 'walkway', 1105, 1433);
        const central_w141 = new GraphNode('central_w141', 'walkway', 980, 1434);
        const central_w142 = new GraphNode('central_w142', 'walkway', 1093, 1289);
        const north_w143 = new GraphNode('north_w143', 'walkway', 1332, 1163);
        const east_w144 = new GraphNode('east_w144', 'walkway', 1441, 1147);
        const east_w145 = new GraphNode('east_w145', 'walkway', 1797, 1093);
        const east_w146 = new GraphNode('east_w146', 'walkway', 1842, 1383);
        const east_w147 = new GraphNode('east_w147', 'walkway', 1853, 1479);
        const west_w148 = new GraphNode('west_w148', 'walkway', 652, 831);
        const central_w150 = new GraphNode('central_w150', 'walkway', 1350, 1553);
        const east_w151 = new GraphNode('east_w151', 'walkway', 1566, 2020);
        const central_w152 = new GraphNode('central_w152', 'walkway', 1267, 1893);
        const central_w153 = new GraphNode('central_w153', 'walkway', 1433, 1950);
        const east_w154 = new GraphNode('east_w154', 'walkway', 1450, 2138);
        const east_w155 = new GraphNode('east_w155', 'walkway', 1627, 2158);
        const central_w156 = new GraphNode('central_w156', 'walkway', 1213, 2339);
        const central_w157 = new GraphNode('central_w157', 'walkway', 1170, 2011);
        const central_w158 = new GraphNode('central_w158', 'walkway', 1175, 2124);
        const central_w159 = new GraphNode('central_w159', 'walkway', 1174, 2296);
        const central_w160 = new GraphNode('central_w160', 'walkway', 1011, 2280);
        const central_w161 = new GraphNode('central_w161', 'walkway', 941, 2277);
        const central_w162 = new GraphNode('central_w162', 'walkway', 942, 2214);
        const central_w163 = new GraphNode('central_w163', 'walkway', 892, 2218);
        const central_w164 = new GraphNode('central_w164', 'walkway', 1116, 2062);
        const central_w165 = new GraphNode('central_w165', 'walkway', 1068, 2013);
        const central_w166 = new GraphNode('central_w166', 'walkway', 1010, 2051);
        const central_w167 = new GraphNode('central_w167', 'walkway', 1309, 2364);
        const central_w168 = new GraphNode('central_w168', 'walkway', 1392, 2158);
        const south_w169 = new GraphNode('south_w169', 'walkway', 1341, 2632);
        const east_w170 = new GraphNode('east_w170', 'walkway', 1447, 2629);
        const east_w171 = new GraphNode('east_w171', 'walkway', 1478, 2594);
        const east_w172 = new GraphNode('east_w172', 'walkway', 1610, 2593);
        const east_w173 = new GraphNode('east_w173', 'walkway', 1635, 2666);
        const east_w174 = new GraphNode('east_w174', 'walkway', 1614, 2688);
        const east_w175 = new GraphNode('east_w175', 'walkway', 1705, 2683);
        const east_b18 = new GraphNode('east_b18', 'building', 1532, 2700);
        const south_w176 = new GraphNode('south_w176', 'walkway', 1322, 2417);
        const south_w177 = new GraphNode('south_w177', 'walkway', 1244, 2486);
        const south_w178 = new GraphNode('south_w178', 'walkway', 1424, 2491);
        const south_w179 = new GraphNode('south_w179', 'walkway', 1331, 2554);
        const east_w180 = new GraphNode('east_w180', 'walkway', 1693, 2466);
        const east_w181 = new GraphNode('east_w181', 'walkway', 1705, 2588);
        const east_w183 = new GraphNode('east_w183', 'walkway', 1499, 2468);
        const east_w184 = new GraphNode('east_w184', 'walkway', 1744, 2758);
        const east_w185 = new GraphNode('east_w185', 'walkway', 1737, 2886);
        const central_w186 = new GraphNode('central_w186', 'walkway', 764, 1641);
        const central_w187 = new GraphNode('central_w187', 'walkway', 824, 1614);
        const central_w188 = new GraphNode('central_w188', 'walkway', 764, 1540);
        const west_w189 = new GraphNode('west_w189', 'walkway', 690, 1537);
        const west_w190 = new GraphNode('west_w190', 'walkway', 719, 1457);
        const central_w191 = new GraphNode('central_w191', 'walkway', 766, 1399);
        const central_w192 = new GraphNode('central_w192', 'walkway', 735, 1309);
        const west_w193 = new GraphNode('west_w193', 'walkway', 592, 1586);
        const west_w194 = new GraphNode('west_w194', 'walkway', 594, 1643);
        const west_w196 = new GraphNode('west_w196', 'walkway', 512, 1579);
        const west_w197 = new GraphNode('west_w197', 'walkway', 592, 1537);
        const central_w198 = new GraphNode('central_w198', 'walkway', 762, 1756);
        const west_w199 = new GraphNode('west_w199', 'walkway', 589, 1753);
        const north_w200 = new GraphNode('north_w200', 'walkway', 737, 1081);
        const north_w201 = new GraphNode('north_w201', 'walkway', 1236, 849);
        const north_w202 = new GraphNode('north_w202', 'walkway', 1262, 1007);
        const north_w203 = new GraphNode('north_w203', 'walkway', 1305, 584);
        const north_w204 = new GraphNode('north_w204', 'walkway', 1245, 314);
        const east_w196 = new GraphNode('east_w196', 'walkway', 1729, 1918);
        const east_w197 = new GraphNode('east_w197', 'walkway', 1797, 1724);
        const east_w198 = new GraphNode('east_w198', 'walkway', 1727, 1722);
        const east_w199 = new GraphNode('east_w199', 'walkway', 1732, 1911);

        // Add Nodes to Hashmap for fast lookup
        // --- Custom Gate & Building keys ---
        this.buildingGraph.set('main gate', south_g4);
        this.buildingGraph.set('walkin gate', east_g5);
        this.buildingGraph.set('back gate', east_g6);

        this.buildingGraph.set('building3', east_b3);
        this.buildingGraph.set('building1', east_b4);
        this.buildingGraph.set('building2', east_b6);
        this.buildingGraph.set('building8', central_b7);
        this.buildingGraph.set('building18', north_b9);
        this.buildingGraph.set('lt49', west_b11);
        this.buildingGraph.set('building47', west_b12);
        this.buildingGraph.set('building4', central_b13);
        this.buildingGraph.set('building5', central_b14);
        this.buildingGraph.set('building22', central_b15);
        this.buildingGraph.set('building45', west_b16);

        // --- Walkway keys (friendly form: w###) ---

        this.buildingGraph.set('w1', south_w1);
        this.buildingGraph.set('w2', south_w2);
        this.buildingGraph.set('w4', south_w4);
        this.buildingGraph.set('w5', central_w5);
        this.buildingGraph.set('w6', central_w6);
        this.buildingGraph.set('w7', east_w7);
        this.buildingGraph.set('w8', east_w8);
        this.buildingGraph.set('w9', east_w9);
        this.buildingGraph.set('w10', east_w10);
        this.buildingGraph.set('w11', south_w11);
        this.buildingGraph.set('w12', east_w12);
        this.buildingGraph.set('w13', east_w13);
        this.buildingGraph.set('w14', east_w14);
        this.buildingGraph.set('w15', east_w15);
        this.buildingGraph.set('w16', east_w16);
        this.buildingGraph.set('w17', east_w17);
        this.buildingGraph.set('w18', east_w18);
        this.buildingGraph.set('w19', east_w19);
        this.buildingGraph.set('w20', east_w20);
        this.buildingGraph.set('w21', east_w21);
        this.buildingGraph.set('w22', east_w22);
        this.buildingGraph.set('w23', east_w23);
        this.buildingGraph.set('w24', east_w24);
        this.buildingGraph.set('w25', east_w25);
        this.buildingGraph.set('w26', east_w26);
        this.buildingGraph.set('w27', east_w27);
        this.buildingGraph.set('w28', east_w28);
        this.buildingGraph.set('w29', east_w29);
        this.buildingGraph.set('w30', east_w30);
        this.buildingGraph.set('w31', east_w31);
        this.buildingGraph.set('w32', east_w32);
        this.buildingGraph.set('w33', east_w33);

        this.buildingGraph.set('w35', central_w35);
        this.buildingGraph.set('w36', central_w36);
        this.buildingGraph.set('w37', east_w37);
        this.buildingGraph.set('w38', east_w38);

        this.buildingGraph.set('w39', north_w39);
        this.buildingGraph.set('w40', north_w40);

        this.buildingGraph.set('w41', east_w41);
        this.buildingGraph.set('w42', east_w42);
        this.buildingGraph.set('w43', east_w43);
        this.buildingGraph.set('w44', east_w44);
        this.buildingGraph.set('w45', east_w45);
        this.buildingGraph.set('w46', east_w46);
        this.buildingGraph.set('w47', east_w47);

        this.buildingGraph.set('w48', north_w48);
        this.buildingGraph.set('w49', north_w49);

        this.buildingGraph.set('w50', central_w50);
        this.buildingGraph.set('w51', north_w51);
        this.buildingGraph.set('w52', west_w52);
        this.buildingGraph.set('w53', north_w53);
        this.buildingGraph.set('w54', north_w54);
        this.buildingGraph.set('w55', north_w55);
        this.buildingGraph.set('w56', north_w56);
        this.buildingGraph.set('w57', north_w57);

        this.buildingGraph.set('w58', west_w58);
        this.buildingGraph.set('w59', west_w59);
        this.buildingGraph.set('w60', west_w60);
        this.buildingGraph.set('w61', west_w61);
        this.buildingGraph.set('w62', west_w62);
        this.buildingGraph.set('w63', west_w63);
        this.buildingGraph.set('w64', west_w64);
        this.buildingGraph.set('w65', west_w65);
        this.buildingGraph.set('w66', west_w66);

        this.buildingGraph.set('w67', central_w67);
        this.buildingGraph.set('w68', west_w68);
        this.buildingGraph.set('w69', west_w69);
        this.buildingGraph.set('w70', west_w70);
        this.buildingGraph.set('w71', west_w71);

        this.buildingGraph.set('w72', central_w72);
        this.buildingGraph.set('w73', central_w73);
        this.buildingGraph.set('w74', central_w74);
        this.buildingGraph.set('w75', central_w75);
        this.buildingGraph.set('w76', central_w76);
        this.buildingGraph.set('w77', central_w77);
        this.buildingGraph.set('w78', central_w78);
        this.buildingGraph.set('w79', central_w79);
        this.buildingGraph.set('w80', central_w80);
        this.buildingGraph.set('w81', central_w81);
        this.buildingGraph.set('w82', central_w82);
        this.buildingGraph.set('w83', central_w83);
        this.buildingGraph.set('w84', central_w84);
        this.buildingGraph.set('w85', central_w85);
        this.buildingGraph.set('w86', central_w86);

        this.buildingGraph.set('w88', central_w88);
        this.buildingGraph.set('w89', central_w89);
        this.buildingGraph.set('w90', central_w90);

        this.buildingGraph.set('w91', west_w91);
        this.buildingGraph.set('w92', west_w92);

        this.buildingGraph.set('w93', central_w93);
        this.buildingGraph.set('w94', central_w94);

        this.buildingGraph.set('w96', central_w96);
        this.buildingGraph.set('w97', central_w97);
        this.buildingGraph.set('w98', central_w98);
        this.buildingGraph.set('w99', central_w99);

        this.buildingGraph.set('w100', west_w100);
        this.buildingGraph.set('w101', west_w101);
        this.buildingGraph.set('w102', west_w102);
        this.buildingGraph.set('w103', west_w103);

        this.buildingGraph.set('w104', south_w104);
        this.buildingGraph.set('w105', west_w105);
        this.buildingGraph.set('w106', west_w106);
        this.buildingGraph.set('w107', west_w107);
        this.buildingGraph.set('w108', west_w108);
        this.buildingGraph.set('w109', west_w109);
        this.buildingGraph.set('w110', west_w110);
        this.buildingGraph.set('w111', west_w111);
        this.buildingGraph.set('w112', west_w112);
        this.buildingGraph.set('w113', west_w113);

        this.buildingGraph.set('w114', west_w114);
        this.buildingGraph.set('w115', west_w115);

        this.buildingGraph.set('w116', central_w116);
        this.buildingGraph.set('w117', central_w117);
        this.buildingGraph.set('w118', central_w118);
        this.buildingGraph.set('w119', central_w119);
        this.buildingGraph.set('w120', central_w120);

        this.buildingGraph.set('w121', east_w121);
        this.buildingGraph.set('w122', east_w122);

        this.buildingGraph.set('w123', central_w123);
        this.buildingGraph.set('w124', central_w124);

        this.buildingGraph.set('w126', central_w126);
        this.buildingGraph.set('w127', central_w127);
        this.buildingGraph.set('w128', central_w128);
        this.buildingGraph.set('w129', central_w129);
        this.buildingGraph.set('w130', central_w130);

        this.buildingGraph.set('w131', east_w131);
        this.buildingGraph.set('w132', east_w132);
        this.buildingGraph.set('w133', east_w133);

        this.buildingGraph.set('w134', central_w134);
        this.buildingGraph.set('w135', central_w135);
        this.buildingGraph.set('w136', central_w136);
        this.buildingGraph.set('w137', central_w137);

        this.buildingGraph.set('w139', central_w139);
        this.buildingGraph.set('w140', central_w140);
        this.buildingGraph.set('w141', central_w141);
        this.buildingGraph.set('w142', central_w142);
        this.buildingGraph.set('w143', north_w143);

        this.buildingGraph.set('w144', east_w144);
        this.buildingGraph.set('w145', east_w145);
        this.buildingGraph.set('w146', east_w146);
        this.buildingGraph.set('w147', east_w147);

        this.buildingGraph.set('w148', west_w148);

        this.buildingGraph.set('w150', central_w150);
        this.buildingGraph.set('w151', east_w151);
        this.buildingGraph.set('w152', central_w152);
        this.buildingGraph.set('w153', central_w153);
        this.buildingGraph.set('w154', east_w154);
        this.buildingGraph.set('w155', east_w155);

        this.buildingGraph.set('w156', central_w156);
        this.buildingGraph.set('w157', central_w157);
        this.buildingGraph.set('w158', central_w158);
        this.buildingGraph.set('w159', central_w159);

        this.buildingGraph.set('w160', central_w160);
        this.buildingGraph.set('w161', central_w161);
        this.buildingGraph.set('w162', central_w162);
        this.buildingGraph.set('w163', central_w163);
        this.buildingGraph.set('w164', central_w164);
        this.buildingGraph.set('w165', central_w165);
        this.buildingGraph.set('w166', central_w166);
        this.buildingGraph.set('w167', central_w167);
        this.buildingGraph.set('w168', central_w168);

        this.buildingGraph.set('w169', south_w169);

        this.buildingGraph.set('w170', east_w170);
        this.buildingGraph.set('w171', east_w171);
        this.buildingGraph.set('w172', east_w172);
        this.buildingGraph.set('w173', east_w173);
        this.buildingGraph.set('w174', east_w174);
        this.buildingGraph.set('w175', east_w175);

        this.buildingGraph.set('w176', south_w176);
        this.buildingGraph.set('w177', south_w177);
        this.buildingGraph.set('w178', south_w178);
        this.buildingGraph.set('w179', south_w179);

        this.buildingGraph.set('w180', east_w180);
        this.buildingGraph.set('w181', east_w181);

        this.buildingGraph.set('w183', east_w183);
        this.buildingGraph.set('w184', east_w184);
        this.buildingGraph.set('w185', east_w185);

        this.buildingGraph.set('w186', central_w186);
        this.buildingGraph.set('w187', central_w187);
        this.buildingGraph.set('w188', central_w188);

        this.buildingGraph.set('w189', west_w189);
        this.buildingGraph.set('w190', west_w190);

        this.buildingGraph.set('w191', central_w191);
        this.buildingGraph.set('w192', central_w192);

        this.buildingGraph.set('w193', west_w193);
        this.buildingGraph.set('w194', west_w194);

        this.buildingGraph.set('w196', west_w196);
        this.buildingGraph.set('w197', west_w197);

        this.buildingGraph.set('w198', central_w198);
        this.buildingGraph.set('w199', west_w199);

        this.buildingGraph.set('w200', north_w200);
        this.buildingGraph.set('w201', north_w201);
        this.buildingGraph.set('w202', north_w202);
        this.buildingGraph.set('w203', north_w203);
        this.buildingGraph.set('w204', north_w204);

        // Edges
        south_g4.addBidirectionalNeighbor(south_w1);
        south_w11.addBidirectionalNeighbor(south_w1);
        south_w2.addBidirectionalNeighbor(south_w1);
        east_w8.addBidirectionalNeighbor(east_w9);
        east_w9.addBidirectionalNeighbor(east_w10);
        east_w10.addBidirectionalNeighbor(east_w17);
        east_w17.addBidirectionalNeighbor(east_w16);
        east_w17.addBidirectionalNeighbor(east_w18);
        east_w18.addBidirectionalNeighbor(east_w19);
        east_w19.addBidirectionalNeighbor(east_w20);
        east_w20.addBidirectionalNeighbor(east_w21);
        east_w21.addBidirectionalNeighbor(east_w13);
        east_w13.addBidirectionalNeighbor(east_w14);
        east_w14.addBidirectionalNeighbor(east_w15);
        east_w13.addBidirectionalNeighbor(east_w12);
        east_g5.addBidirectionalNeighbor(east_w13);
        east_w15.addBidirectionalNeighbor(east_w16);
        east_w12.addBidirectionalNeighbor(south_w11);
        south_w4.addBidirectionalNeighbor(central_w99);
        central_w98.addBidirectionalNeighbor(central_w99);
        central_w98.addBidirectionalNeighbor(south_w104);
        south_w104.addBidirectionalNeighbor(west_w105);
        west_w105.addBidirectionalNeighbor(west_w106);
        west_w106.addBidirectionalNeighbor(west_w107);
        west_w107.addBidirectionalNeighbor(west_w108);
        west_w108.addBidirectionalNeighbor(west_w109);
        west_w113.addBidirectionalNeighbor(west_w109);
        west_w112.addBidirectionalNeighbor(west_w109);
        west_w113.addBidirectionalNeighbor(west_b16);
        west_w110.addBidirectionalNeighbor(west_w113);
        west_w110.addBidirectionalNeighbor(west_w111);
        west_w111.addBidirectionalNeighbor(west_w112);
        central_w98.addBidirectionalNeighbor(west_w92);
        central_w98.addBidirectionalNeighbor(central_w96);
        central_w96.addBidirectionalNeighbor(central_w97);
        central_w96.addBidirectionalNeighbor(central_w94);
        central_w94.addBidirectionalNeighbor(central_w93);
        central_w93.addBidirectionalNeighbor(central_w88);
        central_w88.addBidirectionalNeighbor(central_w89);
        central_w89.addBidirectionalNeighbor(central_w90);
        central_w90.addBidirectionalNeighbor(west_w91);
        west_w91.addBidirectionalNeighbor(west_w92);
        west_w92.addBidirectionalNeighbor(west_w100);
        west_w100.addBidirectionalNeighbor(west_w101);
        west_w101.addBidirectionalNeighbor(west_w102);
        west_w102.addBidirectionalNeighbor(west_w103);
        west_w103.addBidirectionalNeighbor(west_w71);
        west_w114.addBidirectionalNeighbor(west_w71);
        west_w114.addBidirectionalNeighbor(west_w70);
        central_w72.addBidirectionalNeighbor(west_w71);
        central_w72.addBidirectionalNeighbor(central_w73);
        central_w86.addBidirectionalNeighbor(central_w85);
        central_w85.addBidirectionalNeighbor(central_w86);
        central_w85.addBidirectionalNeighbor(central_w84);
        central_w73.addBidirectionalNeighbor(central_w74);
        central_w74.addBidirectionalNeighbor(central_w75);
        central_w75.addBidirectionalNeighbor(central_w76);
        central_w76.addBidirectionalNeighbor(central_w77);
        central_w75.addBidirectionalNeighbor(central_w78);
        central_w78.addBidirectionalNeighbor(central_w79);
        central_w79.addBidirectionalNeighbor(central_w77);
        central_w79.addBidirectionalNeighbor(central_w80);
        central_w80.addBidirectionalNeighbor(central_w81);
        central_w81.addBidirectionalNeighbor(central_w82);
        central_w82.addBidirectionalNeighbor(central_w83);
        central_w83.addBidirectionalNeighbor(central_w84);
        central_w36.addBidirectionalNeighbor(central_w80);
        west_w68.addBidirectionalNeighbor(west_w65);
        west_w68.addBidirectionalNeighbor(west_w69);
        west_w65.addBidirectionalNeighbor(west_w64);
        west_w65.addBidirectionalNeighbor(west_w66);
        west_w64.addBidirectionalNeighbor(west_w115);
        west_w115.addBidirectionalNeighbor(west_w63);
        west_w63.addBidirectionalNeighbor(west_w52);
        west_w52.addBidirectionalNeighbor(west_w62);
        west_w52.addBidirectionalNeighbor(west_w58);
        west_w52.addBidirectionalNeighbor(west_w59);
        west_w59.addBidirectionalNeighbor(west_w60);
        west_w59.addBidirectionalNeighbor(west_w61);
        west_w58.addBidirectionalNeighbor(north_w51);
        west_w148.addBidirectionalNeighbor(west_w58);
        central_w50.addBidirectionalNeighbor(north_w51);
        central_w50.addBidirectionalNeighbor(central_w67);
        west_w66.addBidirectionalNeighbor(central_w67);
        central_w50.addBidirectionalNeighbor(north_w40);
        north_w40.addBidirectionalNeighbor(central_w142);
        central_w139.addBidirectionalNeighbor(central_w142);
        central_w139.addBidirectionalNeighbor(central_w137);
        central_w139.addBidirectionalNeighbor(central_w140);
        central_w141.addBidirectionalNeighbor(central_w140);
        central_w36.addBidirectionalNeighbor(central_w140);
        central_w36.addBidirectionalNeighbor(central_w35);
        central_w35.addBidirectionalNeighbor(central_w126);
        central_w126.addBidirectionalNeighbor(central_w127);
        central_w127.addBidirectionalNeighbor(central_w128);
        central_w128.addBidirectionalNeighbor(central_w129);
        central_w129.addBidirectionalNeighbor(central_w134);
        central_w134.addBidirectionalNeighbor(central_w135);
        central_w135.addBidirectionalNeighbor(central_w137);
        central_w129.addBidirectionalNeighbor(east_w133);
        east_w132.addBidirectionalNeighbor(east_w133);
        east_w132.addBidirectionalNeighbor(east_w131);
        east_w131.addBidirectionalNeighbor(central_w126);
        east_w133.addBidirectionalNeighbor(central_w130);
        central_w129.addBidirectionalNeighbor(central_w130);
        central_w135.addBidirectionalNeighbor(central_w136);
        central_w142.addBidirectionalNeighbor(central_w136);
        central_w136.addBidirectionalNeighbor(north_w39);
        north_w40.addBidirectionalNeighbor(north_w39);
        north_w39.addBidirectionalNeighbor(north_b9);
        north_w39.addBidirectionalNeighbor(north_w143);
        north_w143.addBidirectionalNeighbor(east_w144);
        east_w144.addBidirectionalNeighbor(central_w130);
        north_w143.addBidirectionalNeighbor(central_w130);
        east_w144.addBidirectionalNeighbor(east_w38);
        east_w37.addBidirectionalNeighbor(east_w38);
        east_w37.addBidirectionalNeighbor(east_w145);
        east_w37.addBidirectionalNeighbor(east_w33);
        east_w33.addBidirectionalNeighbor(east_w146);
        east_w146.addBidirectionalNeighbor(east_w147);
        east_w33.addBidirectionalNeighbor(east_w131);
        east_w32.addBidirectionalNeighbor(east_w33);
        east_w32.addBidirectionalNeighbor(east_w29);
        east_w29.addBidirectionalNeighbor(east_w30);
        east_w30.addBidirectionalNeighbor(east_w31);
        central_w124.addBidirectionalNeighbor(central_w123);
        east_w30.addBidirectionalNeighbor(central_b7);
        central_w35.addBidirectionalNeighbor(central_w150);
        central_w150.addBidirectionalNeighbor(central_w126);
        central_w150.addBidirectionalNeighbor(central_b7);
        central_b7.addBidirectionalNeighbor(central_w124);
        east_w122.addBidirectionalNeighbor(east_w31);
        east_w122.addBidirectionalNeighbor(east_w121);
        east_w28.addBidirectionalNeighbor(east_w29);
        east_w27.addBidirectionalNeighbor(east_w28);
        east_w26.addBidirectionalNeighbor(east_w27);
        east_w26.addBidirectionalNeighbor(east_w25);
        east_w24.addBidirectionalNeighbor(east_w25);
        east_w24.addBidirectionalNeighbor(east_w22);
        east_w22.addBidirectionalNeighbor(east_w23);
        east_w23.addBidirectionalNeighbor(east_b3);
        east_w151.addBidirectionalNeighbor(east_w26);
        east_w31.addBidirectionalNeighbor(east_b6);
        central_w120.addBidirectionalNeighbor(east_w121);
        central_w123.addBidirectionalNeighbor(central_w120);
        central_w152.addBidirectionalNeighbor(central_w120);
        central_w152.addBidirectionalNeighbor(central_b15);
        central_w152.addBidirectionalNeighbor(central_w119);
        central_w119.addBidirectionalNeighbor(central_w120);
        central_w119.addBidirectionalNeighbor(central_w117);
        central_w117.addBidirectionalNeighbor(central_b14);
        central_w119.addBidirectionalNeighbor(central_b14);
        central_w86.addBidirectionalNeighbor(central_b14);
        central_w85.addBidirectionalNeighbor(central_b15);
        central_w116.addBidirectionalNeighbor(central_w117);
        central_w117.addBidirectionalNeighbor(central_w118);
        central_w116.addBidirectionalNeighbor(central_w118);
        central_w5.addBidirectionalNeighbor(central_w116);
        central_w6.addBidirectionalNeighbor(central_w5);
        central_w119.addBidirectionalNeighbor(central_w153);
        east_w151.addBidirectionalNeighbor(central_w153);
        east_w154.addBidirectionalNeighbor(east_w151);
        east_w154.addBidirectionalNeighbor(east_b3);
        central_w118.addBidirectionalNeighbor(east_w154);
        east_w154.addBidirectionalNeighbor(east_w155);
        east_w24.addBidirectionalNeighbor(east_w155);
        east_w155.addBidirectionalNeighbor(east_w23);
        east_w22.addBidirectionalNeighbor(east_w9);
        south_w4.addBidirectionalNeighbor(central_w156);
        central_w156.addBidirectionalNeighbor(central_w5);
        central_w6.addBidirectionalNeighbor(central_w158);
        central_b13.addBidirectionalNeighbor(central_w158);
        central_w157.addBidirectionalNeighbor(central_w158);
        central_w158.addBidirectionalNeighbor(central_w117);
        central_w161.addBidirectionalNeighbor(central_w160);
        central_w161.addBidirectionalNeighbor(central_w162);
        central_w162.addBidirectionalNeighbor(central_w163);
        central_w163.addBidirectionalNeighbor(central_w97);
        central_w160.addBidirectionalNeighbor(central_w159);
        central_w159.addBidirectionalNeighbor(central_w156);
        central_w159.addBidirectionalNeighbor(central_w6);
        central_w88.addBidirectionalNeighbor(central_w166);
        central_w166.addBidirectionalNeighbor(central_w165);
        central_w165.addBidirectionalNeighbor(central_w164);
        central_w165.addBidirectionalNeighbor(central_w86);
        central_w164.addBidirectionalNeighbor(central_w157);
        central_w157.addBidirectionalNeighbor(central_w158);
        central_w167.addBidirectionalNeighbor(central_w116);
        central_w168.addBidirectionalNeighbor(central_w116);
        central_w168.addBidirectionalNeighbor(east_w154);
        south_w2.addBidirectionalNeighbor(south_w169);
        south_w169.addBidirectionalNeighbor(east_w170);
        east_w170.addBidirectionalNeighbor(east_w171);
        south_w4.addBidirectionalNeighbor(south_w177);
        south_w177.addBidirectionalNeighbor(south_w176);
        south_w176.addBidirectionalNeighbor(south_w178);
        south_w179.addBidirectionalNeighbor(south_w178);
        south_w179.addBidirectionalNeighbor(south_w177);
        south_w179.addBidirectionalNeighbor(south_w169);
        central_w167.addBidirectionalNeighbor(south_w176);
        south_w178.addBidirectionalNeighbor(east_w7);
        east_w171.addBidirectionalNeighbor(east_w172);
        east_w172.addBidirectionalNeighbor(east_w173);
        east_w173.addBidirectionalNeighbor(east_w174);
        east_w174.addBidirectionalNeighbor(east_w175);
        east_w174.addBidirectionalNeighbor(east_b18);
        east_w173.addBidirectionalNeighbor(east_w175);
        east_w9.addBidirectionalNeighbor(east_w180);
        east_w180.addBidirectionalNeighbor(east_w172);
        east_w172.addBidirectionalNeighbor(east_w7);
        east_w7.addBidirectionalNeighbor(east_w183);
        east_w183.addBidirectionalNeighbor(east_w8);
        east_w175.addBidirectionalNeighbor(east_w181);
        east_w181.addBidirectionalNeighbor(east_w180);
        east_w175.addBidirectionalNeighbor(east_w184);
        east_w184.addBidirectionalNeighbor(east_w185);
        east_w13.addBidirectionalNeighbor(east_w185);
        central_w192.addBidirectionalNeighbor(central_w67);
        central_w192.addBidirectionalNeighbor(west_b12);
        west_b12.addBidirectionalNeighbor(central_w191);
        west_b12.addBidirectionalNeighbor(west_w190);
        west_w189.addBidirectionalNeighbor(west_w190);
        west_w189.addBidirectionalNeighbor(central_w188);
        west_w190.addBidirectionalNeighbor(central_w191);
        central_w186.addBidirectionalNeighbor(central_w188);
        central_w186.addBidirectionalNeighbor(west_b11);
        west_w70.addBidirectionalNeighbor(west_w196);
        west_w68.addBidirectionalNeighbor(west_w196);
        west_w196.addBidirectionalNeighbor(west_w193);
        west_w193.addBidirectionalNeighbor(west_w194);
        west_w194.addBidirectionalNeighbor(west_b11);
        west_w189.addBidirectionalNeighbor(west_w197);
        west_w197.addBidirectionalNeighbor(west_w193);
        central_w186.addBidirectionalNeighbor(central_w187);
        central_w186.addBidirectionalNeighbor(central_w198);
        west_w199.addBidirectionalNeighbor(central_w198);
        west_w199.addBidirectionalNeighbor(west_w194);
        central_w187.addBidirectionalNeighbor(central_w76);
        north_w51.addBidirectionalNeighbor(north_w200);
        north_w200.addBidirectionalNeighbor(central_w50);
        north_w51.addBidirectionalNeighbor(north_w53);
        north_w51.addBidirectionalNeighbor(north_w55);
        north_w55.addBidirectionalNeighbor(north_w56);
        north_w56.addBidirectionalNeighbor(north_w57);
        north_w55.addBidirectionalNeighbor(north_w54);
        north_w54.addBidirectionalNeighbor(north_w53);
        north_w53.addBidirectionalNeighbor(north_w54);
        north_w48.addBidirectionalNeighbor(north_w54);
        north_w48.addBidirectionalNeighbor(north_w49);
        north_w49.addBidirectionalNeighbor(north_w57);
        north_w202.addBidirectionalNeighbor(north_w201);
        north_w201.addBidirectionalNeighbor(north_w48);
        north_w48.addBidirectionalNeighbor(east_w46);
        east_w46.addBidirectionalNeighbor(east_w45);
        east_w45.addBidirectionalNeighbor(east_w44);
        east_w44.addBidirectionalNeighbor(east_w43);
        east_w47.addBidirectionalNeighbor(east_w46);
        east_w47.addBidirectionalNeighbor(east_w38);
        north_w57.addBidirectionalNeighbor(north_w204);
        north_w48.addBidirectionalNeighbor(north_w203);
        east_w43.addBidirectionalNeighbor(east_w42);
        east_w41.addBidirectionalNeighbor(east_w42);
        east_w41.addBidirectionalNeighbor(east_g6);
        south_g4.addBidirectionalNeighbor(south_w1);
        south_w11.addBidirectionalNeighbor(south_w1);
        south_w2.addBidirectionalNeighbor(south_w1);
        east_w8.addBidirectionalNeighbor(east_w9);
        east_w9.addBidirectionalNeighbor(east_w10);
        east_w10.addBidirectionalNeighbor(east_w17);
        east_w17.addBidirectionalNeighbor(east_w16);
        east_w17.addBidirectionalNeighbor(east_w18);
        east_w18.addBidirectionalNeighbor(east_w19);
        east_w19.addBidirectionalNeighbor(east_w20);
        east_w20.addBidirectionalNeighbor(east_w21);
        east_w21.addBidirectionalNeighbor(east_w13);
        east_w13.addBidirectionalNeighbor(east_w14);
        east_w14.addBidirectionalNeighbor(east_w15);
        east_w13.addBidirectionalNeighbor(east_w12);
        east_g5.addBidirectionalNeighbor(east_w13);
        east_w15.addBidirectionalNeighbor(east_w16);
        east_w12.addBidirectionalNeighbor(south_w11);
        south_w4.addBidirectionalNeighbor(central_w99);
        central_w98.addBidirectionalNeighbor(central_w99);
        central_w98.addBidirectionalNeighbor(south_w104);
        south_w104.addBidirectionalNeighbor(west_w105);
        west_w105.addBidirectionalNeighbor(west_w106);
        west_w106.addBidirectionalNeighbor(west_w107);
        west_w107.addBidirectionalNeighbor(west_w108);
        west_w108.addBidirectionalNeighbor(west_w109);
        west_w113.addBidirectionalNeighbor(west_w109);
        west_w112.addBidirectionalNeighbor(west_w109);
        west_w113.addBidirectionalNeighbor(west_b16);
        west_w110.addBidirectionalNeighbor(west_w113);
        west_w110.addBidirectionalNeighbor(west_w111);
        west_w111.addBidirectionalNeighbor(west_w112);
        central_w98.addBidirectionalNeighbor(west_w92);
        central_w98.addBidirectionalNeighbor(central_w96);
        central_w96.addBidirectionalNeighbor(central_w97);
        central_w96.addBidirectionalNeighbor(central_w94);
        central_w94.addBidirectionalNeighbor(central_w93);
        central_w93.addBidirectionalNeighbor(central_w88);
        central_w88.addBidirectionalNeighbor(central_w89);
        central_w89.addBidirectionalNeighbor(central_w90);
        central_w90.addBidirectionalNeighbor(west_w91);
        west_w91.addBidirectionalNeighbor(west_w92);
        west_w92.addBidirectionalNeighbor(west_w100);
        west_w100.addBidirectionalNeighbor(west_w101);
        west_w101.addBidirectionalNeighbor(west_w102);
        west_w102.addBidirectionalNeighbor(west_w103);
        west_w103.addBidirectionalNeighbor(west_w71);
        west_w114.addBidirectionalNeighbor(west_w71);
        west_w114.addBidirectionalNeighbor(west_w70);
        central_w72.addBidirectionalNeighbor(west_w71);
        central_w72.addBidirectionalNeighbor(central_w73);
        central_w86.addBidirectionalNeighbor(central_w85);
        central_w85.addBidirectionalNeighbor(central_w86);
        central_w85.addBidirectionalNeighbor(central_w84);
        central_w73.addBidirectionalNeighbor(central_w74);
        central_w74.addBidirectionalNeighbor(central_w75);
        central_w75.addBidirectionalNeighbor(central_w76);
        central_w76.addBidirectionalNeighbor(central_w77);
        central_w75.addBidirectionalNeighbor(central_w78);
        central_w78.addBidirectionalNeighbor(central_w79);
        central_w79.addBidirectionalNeighbor(central_w77);
        central_w79.addBidirectionalNeighbor(central_w80);
        central_w80.addBidirectionalNeighbor(central_w81);
        central_w81.addBidirectionalNeighbor(central_w82);
        central_w82.addBidirectionalNeighbor(central_w83);
        central_w83.addBidirectionalNeighbor(central_w84);
        central_w36.addBidirectionalNeighbor(central_w80);
        west_w68.addBidirectionalNeighbor(west_w65);
        west_w68.addBidirectionalNeighbor(west_w69);
        west_w65.addBidirectionalNeighbor(west_w64);
        west_w65.addBidirectionalNeighbor(west_w66);
        west_w64.addBidirectionalNeighbor(west_w115);
        west_w115.addBidirectionalNeighbor(west_w63);
        west_w63.addBidirectionalNeighbor(west_w52);
        west_w52.addBidirectionalNeighbor(west_w62);
        west_w52.addBidirectionalNeighbor(west_w58);
        west_w52.addBidirectionalNeighbor(west_w59);
        west_w59.addBidirectionalNeighbor(west_w60);
        west_w59.addBidirectionalNeighbor(west_w61);
        west_w58.addBidirectionalNeighbor(north_w51);
        west_w148.addBidirectionalNeighbor(west_w58);
        central_w50.addBidirectionalNeighbor(north_w51);
        central_w50.addBidirectionalNeighbor(central_w67);
        west_w66.addBidirectionalNeighbor(central_w67);
        central_w50.addBidirectionalNeighbor(north_w40);
        north_w40.addBidirectionalNeighbor(central_w142);
        central_w139.addBidirectionalNeighbor(central_w142);
        central_w139.addBidirectionalNeighbor(central_w137);
        central_w139.addBidirectionalNeighbor(central_w140);
        central_w141.addBidirectionalNeighbor(central_w140);
        central_w36.addBidirectionalNeighbor(central_w140);
        central_w36.addBidirectionalNeighbor(central_w35);
        central_w35.addBidirectionalNeighbor(central_w126);
        central_w126.addBidirectionalNeighbor(central_w127);
        central_w127.addBidirectionalNeighbor(central_w128);
        central_w128.addBidirectionalNeighbor(central_w129);
        central_w129.addBidirectionalNeighbor(central_w134);
        central_w134.addBidirectionalNeighbor(central_w135);
        central_w135.addBidirectionalNeighbor(central_w137);
        central_w129.addBidirectionalNeighbor(east_w133);
        east_w132.addBidirectionalNeighbor(east_w133);
        east_w132.addBidirectionalNeighbor(east_w131);
        east_w131.addBidirectionalNeighbor(central_w126);
        east_w133.addBidirectionalNeighbor(central_w130);
        central_w129.addBidirectionalNeighbor(central_w130);
        central_w135.addBidirectionalNeighbor(central_w136);
        central_w142.addBidirectionalNeighbor(central_w136);
        central_w136.addBidirectionalNeighbor(north_w39);
        north_w40.addBidirectionalNeighbor(north_w39);
        north_w39.addBidirectionalNeighbor(north_b9);
        north_w39.addBidirectionalNeighbor(north_w143);
        north_w143.addBidirectionalNeighbor(east_w144);
        east_w144.addBidirectionalNeighbor(central_w130);
        north_w143.addBidirectionalNeighbor(central_w130);
        east_w144.addBidirectionalNeighbor(east_w38);
        east_w37.addBidirectionalNeighbor(east_w38);
        east_w37.addBidirectionalNeighbor(east_w145);
        east_w37.addBidirectionalNeighbor(east_w33);
        east_w33.addBidirectionalNeighbor(east_w146);
        east_w146.addBidirectionalNeighbor(east_w147);
        east_w33.addBidirectionalNeighbor(east_w131);
        east_w32.addBidirectionalNeighbor(east_w33);
        east_w32.addBidirectionalNeighbor(east_w29);
        east_w29.addBidirectionalNeighbor(east_w30);
        east_w30.addBidirectionalNeighbor(east_w31);
        central_w124.addBidirectionalNeighbor(central_w123);
        east_w30.addBidirectionalNeighbor(central_b7);
        central_w35.addBidirectionalNeighbor(central_w150);
        central_w150.addBidirectionalNeighbor(central_w126);
        central_w150.addBidirectionalNeighbor(central_b7);
        central_b7.addBidirectionalNeighbor(central_w124);
        east_w122.addBidirectionalNeighbor(east_w31);
        east_w122.addBidirectionalNeighbor(east_w121);
        east_w28.addBidirectionalNeighbor(east_w29);
        east_w27.addBidirectionalNeighbor(east_w28);
        east_w26.addBidirectionalNeighbor(east_w27);
        east_w26.addBidirectionalNeighbor(east_w25);
        east_w24.addBidirectionalNeighbor(east_w25);
        east_w24.addBidirectionalNeighbor(east_w22);
        east_w22.addBidirectionalNeighbor(east_w23);
        east_w23.addBidirectionalNeighbor(east_b3);
        east_w151.addBidirectionalNeighbor(east_w26);
        east_w31.addBidirectionalNeighbor(east_b6);
        central_w120.addBidirectionalNeighbor(east_w121);
        central_w123.addBidirectionalNeighbor(central_w120);
        central_w152.addBidirectionalNeighbor(central_w120);
        central_w152.addBidirectionalNeighbor(central_b15);
        central_w152.addBidirectionalNeighbor(central_w119);
        central_w119.addBidirectionalNeighbor(central_w120);
        central_w119.addBidirectionalNeighbor(central_w117);
        central_w117.addBidirectionalNeighbor(central_b14);
        central_w119.addBidirectionalNeighbor(central_b14);
        central_w86.addBidirectionalNeighbor(central_b14);
        central_w85.addBidirectionalNeighbor(central_b15);
        central_w116.addBidirectionalNeighbor(central_w117);
        central_w117.addBidirectionalNeighbor(central_w118);
        central_w116.addBidirectionalNeighbor(central_w118);
        central_w5.addBidirectionalNeighbor(central_w116);
        central_w6.addBidirectionalNeighbor(central_w5);
        central_w119.addBidirectionalNeighbor(central_w153);
        east_w151.addBidirectionalNeighbor(central_w153);
        east_w154.addBidirectionalNeighbor(east_w151);
        east_w154.addBidirectionalNeighbor(east_b3);
        central_w118.addBidirectionalNeighbor(east_w154);
        east_w154.addBidirectionalNeighbor(east_w155);
        east_w24.addBidirectionalNeighbor(east_w155);
        east_w155.addBidirectionalNeighbor(east_w23);
        east_w22.addBidirectionalNeighbor(east_w9);
        south_w4.addBidirectionalNeighbor(central_w156);
        central_w156.addBidirectionalNeighbor(central_w5);
        central_w6.addBidirectionalNeighbor(central_w158);
        central_b13.addBidirectionalNeighbor(central_w158);
        central_w157.addBidirectionalNeighbor(central_w158);
        central_w158.addBidirectionalNeighbor(central_w117);
        central_w161.addBidirectionalNeighbor(central_w160);
        central_w161.addBidirectionalNeighbor(central_w162);
        central_w162.addBidirectionalNeighbor(central_w163);
        central_w163.addBidirectionalNeighbor(central_w97);
        central_w160.addBidirectionalNeighbor(central_w159);
        central_w159.addBidirectionalNeighbor(central_w156);
        central_w159.addBidirectionalNeighbor(central_w6);
        central_w88.addBidirectionalNeighbor(central_w166);
        central_w166.addBidirectionalNeighbor(central_w165);
        central_w165.addBidirectionalNeighbor(central_w164);
        central_w165.addBidirectionalNeighbor(central_w86);
        central_w164.addBidirectionalNeighbor(central_w157);
        central_w157.addBidirectionalNeighbor(central_w158);
        central_w167.addBidirectionalNeighbor(central_w116);
        central_w168.addBidirectionalNeighbor(central_w116);
        central_w168.addBidirectionalNeighbor(east_w154);
        south_w2.addBidirectionalNeighbor(south_w169);
        south_w169.addBidirectionalNeighbor(east_w170);
        east_w170.addBidirectionalNeighbor(east_w171);
        south_w4.addBidirectionalNeighbor(south_w177);
        south_w177.addBidirectionalNeighbor(south_w176);
        south_w176.addBidirectionalNeighbor(south_w178);
        south_w179.addBidirectionalNeighbor(south_w178);
        south_w179.addBidirectionalNeighbor(south_w177);
        south_w179.addBidirectionalNeighbor(south_w169);
        central_w167.addBidirectionalNeighbor(south_w176);
        south_w178.addBidirectionalNeighbor(east_w7);
        east_w171.addBidirectionalNeighbor(east_w172);
        east_w172.addBidirectionalNeighbor(east_w173);
        east_w173.addBidirectionalNeighbor(east_w174);
        east_w174.addBidirectionalNeighbor(east_w175);
        east_w174.addBidirectionalNeighbor(east_b18);
        east_w173.addBidirectionalNeighbor(east_w175);
        east_w9.addBidirectionalNeighbor(east_w180);
        east_w180.addBidirectionalNeighbor(east_w172);
        east_w172.addBidirectionalNeighbor(east_w7);
        east_w7.addBidirectionalNeighbor(east_w183);
        east_w183.addBidirectionalNeighbor(east_w8);
        east_w175.addBidirectionalNeighbor(east_w181);
        east_w181.addBidirectionalNeighbor(east_w180);
        east_w175.addBidirectionalNeighbor(east_w184);
        east_w184.addBidirectionalNeighbor(east_w185);
        east_w13.addBidirectionalNeighbor(east_w185);
        central_w192.addBidirectionalNeighbor(central_w67);
        central_w192.addBidirectionalNeighbor(west_b12);
        west_b12.addBidirectionalNeighbor(central_w191);
        west_b12.addBidirectionalNeighbor(west_w190);
        west_w189.addBidirectionalNeighbor(west_w190);
        west_w189.addBidirectionalNeighbor(central_w188);
        west_w190.addBidirectionalNeighbor(central_w191);
        central_w186.addBidirectionalNeighbor(central_w188);
        central_w186.addBidirectionalNeighbor(west_b11);
        west_w70.addBidirectionalNeighbor(west_w196);
        west_w68.addBidirectionalNeighbor(west_w196);
        west_w196.addBidirectionalNeighbor(west_w193);
        west_w193.addBidirectionalNeighbor(west_w194);
        west_w194.addBidirectionalNeighbor(west_b11);
        west_w189.addBidirectionalNeighbor(west_w197);
        west_w197.addBidirectionalNeighbor(west_w193);
        central_w186.addBidirectionalNeighbor(central_w187);
        central_w186.addBidirectionalNeighbor(central_w198);
        west_w199.addBidirectionalNeighbor(central_w198);
        west_w199.addBidirectionalNeighbor(west_w194);
        central_w187.addBidirectionalNeighbor(central_w76);
        north_w51.addBidirectionalNeighbor(north_w200);
        north_w200.addBidirectionalNeighbor(central_w50);
        north_w51.addBidirectionalNeighbor(north_w53);
        north_w51.addBidirectionalNeighbor(north_w55);
        north_w55.addBidirectionalNeighbor(north_w56);
        north_w56.addBidirectionalNeighbor(north_w57);
        north_w55.addBidirectionalNeighbor(north_w54);
        north_w54.addBidirectionalNeighbor(north_w53);
        north_w53.addBidirectionalNeighbor(north_w54);
        north_w48.addBidirectionalNeighbor(north_w54);
        north_w48.addBidirectionalNeighbor(north_w49);
        north_w49.addBidirectionalNeighbor(north_w57);
        north_w202.addBidirectionalNeighbor(north_w201);
        north_w201.addBidirectionalNeighbor(north_w48);
        north_w48.addBidirectionalNeighbor(east_w46);
        east_w46.addBidirectionalNeighbor(east_w45);
        east_w45.addBidirectionalNeighbor(east_w44);
        east_w44.addBidirectionalNeighbor(east_w43);
        east_w47.addBidirectionalNeighbor(east_w46);
        east_w47.addBidirectionalNeighbor(east_w38);
        north_w57.addBidirectionalNeighbor(north_w204);
        north_w48.addBidirectionalNeighbor(north_w203);
        east_w43.addBidirectionalNeighbor(east_w42);
        east_w41.addBidirectionalNeighbor(east_w42);
        east_w41.addBidirectionalNeighbor(east_g6);
        east_w25.addBidirectionalNeighbor(east_w196);
        east_w196.addBidirectionalNeighbor(east_b4);
        east_w197.addBidirectionalNeighbor(east_b4);
        east_w198.addBidirectionalNeighbor(east_w32);
        east_w198.addBidirectionalNeighbor(east_w197);
        east_w198.addBidirectionalNeighbor(east_w196);
        south_g4.addBidirectionalNeighbor(south_w1);
        south_w11.addBidirectionalNeighbor(south_w1);
        south_w2.addBidirectionalNeighbor(south_w1);
        east_w8.addBidirectionalNeighbor(east_w9);
        east_w9.addBidirectionalNeighbor(east_w10);
        east_w10.addBidirectionalNeighbor(east_w17);
        east_w17.addBidirectionalNeighbor(east_w16);
        east_w17.addBidirectionalNeighbor(east_w18);
        east_w18.addBidirectionalNeighbor(east_w19);
        east_w19.addBidirectionalNeighbor(east_w20);
        east_w20.addBidirectionalNeighbor(east_w21);
        east_w21.addBidirectionalNeighbor(east_w13);
        east_w13.addBidirectionalNeighbor(east_w14);
        east_w14.addBidirectionalNeighbor(east_w15);
        east_w13.addBidirectionalNeighbor(east_w12);
        east_g5.addBidirectionalNeighbor(east_w13);
        east_w15.addBidirectionalNeighbor(east_w16);
        east_w12.addBidirectionalNeighbor(south_w11);
        south_w4.addBidirectionalNeighbor(central_w99);
        central_w98.addBidirectionalNeighbor(central_w99);
        central_w98.addBidirectionalNeighbor(south_w104);
        south_w104.addBidirectionalNeighbor(west_w105);
        west_w105.addBidirectionalNeighbor(west_w106);
        west_w106.addBidirectionalNeighbor(west_w107);
        west_w107.addBidirectionalNeighbor(west_w108);
        west_w108.addBidirectionalNeighbor(west_w109);
        west_w113.addBidirectionalNeighbor(west_w109);
        west_w112.addBidirectionalNeighbor(west_w109);
        west_w113.addBidirectionalNeighbor(west_b16);
        west_w110.addBidirectionalNeighbor(west_w113);
        west_w110.addBidirectionalNeighbor(west_w111);
        west_w111.addBidirectionalNeighbor(west_w112);
        central_w98.addBidirectionalNeighbor(west_w92);
        central_w98.addBidirectionalNeighbor(central_w96);
        central_w96.addBidirectionalNeighbor(central_w97);
        central_w96.addBidirectionalNeighbor(central_w94);
        central_w94.addBidirectionalNeighbor(central_w93);
        central_w93.addBidirectionalNeighbor(central_w88);
        central_w88.addBidirectionalNeighbor(central_w89);
        central_w89.addBidirectionalNeighbor(central_w90);
        central_w90.addBidirectionalNeighbor(west_w91);
        west_w91.addBidirectionalNeighbor(west_w92);
        west_w92.addBidirectionalNeighbor(west_w100);
        west_w100.addBidirectionalNeighbor(west_w101);
        west_w101.addBidirectionalNeighbor(west_w102);
        west_w102.addBidirectionalNeighbor(west_w103);
        west_w103.addBidirectionalNeighbor(west_w71);
        west_w114.addBidirectionalNeighbor(west_w71);
        west_w114.addBidirectionalNeighbor(west_w70);
        central_w72.addBidirectionalNeighbor(west_w71);
        central_w72.addBidirectionalNeighbor(central_w73);
        central_w86.addBidirectionalNeighbor(central_w85);
        central_w85.addBidirectionalNeighbor(central_w86);
        central_w85.addBidirectionalNeighbor(central_w84);
        central_w73.addBidirectionalNeighbor(central_w74);
        central_w74.addBidirectionalNeighbor(central_w75);
        central_w75.addBidirectionalNeighbor(central_w76);
        central_w76.addBidirectionalNeighbor(central_w77);
        central_w75.addBidirectionalNeighbor(central_w78);
        central_w78.addBidirectionalNeighbor(central_w79);
        central_w79.addBidirectionalNeighbor(central_w77);
        central_w79.addBidirectionalNeighbor(central_w80);
        central_w80.addBidirectionalNeighbor(central_w81);
        central_w81.addBidirectionalNeighbor(central_w82);
        central_w82.addBidirectionalNeighbor(central_w83);
        central_w83.addBidirectionalNeighbor(central_w84);
        central_w36.addBidirectionalNeighbor(central_w80);
        west_w68.addBidirectionalNeighbor(west_w65);
        west_w68.addBidirectionalNeighbor(west_w69);
        west_w65.addBidirectionalNeighbor(west_w64);
        west_w65.addBidirectionalNeighbor(west_w66);
        west_w64.addBidirectionalNeighbor(west_w115);
        west_w115.addBidirectionalNeighbor(west_w63);
        west_w63.addBidirectionalNeighbor(west_w52);
        west_w52.addBidirectionalNeighbor(west_w62);
        west_w52.addBidirectionalNeighbor(west_w58);
        west_w52.addBidirectionalNeighbor(west_w59);
        west_w59.addBidirectionalNeighbor(west_w60);
        west_w59.addBidirectionalNeighbor(west_w61);
        west_w58.addBidirectionalNeighbor(north_w51);
        west_w148.addBidirectionalNeighbor(west_w58);
        central_w50.addBidirectionalNeighbor(north_w51);
        central_w50.addBidirectionalNeighbor(central_w67);
        west_w66.addBidirectionalNeighbor(central_w67);
        central_w50.addBidirectionalNeighbor(north_w40);
        north_w40.addBidirectionalNeighbor(central_w142);
        central_w139.addBidirectionalNeighbor(central_w142);
        central_w139.addBidirectionalNeighbor(central_w137);
        central_w139.addBidirectionalNeighbor(central_w140);
        central_w141.addBidirectionalNeighbor(central_w140);
        central_w36.addBidirectionalNeighbor(central_w140);
        central_w36.addBidirectionalNeighbor(central_w35);
        central_w35.addBidirectionalNeighbor(central_w126);
        central_w126.addBidirectionalNeighbor(central_w127);
        central_w127.addBidirectionalNeighbor(central_w128);
        central_w128.addBidirectionalNeighbor(central_w129);
        central_w129.addBidirectionalNeighbor(central_w134);
        central_w134.addBidirectionalNeighbor(central_w135);
        central_w135.addBidirectionalNeighbor(central_w137);
        central_w129.addBidirectionalNeighbor(east_w133);
        east_w132.addBidirectionalNeighbor(east_w133);
        east_w132.addBidirectionalNeighbor(east_w131);
        east_w131.addBidirectionalNeighbor(central_w126);
        east_w133.addBidirectionalNeighbor(central_w130);
        central_w129.addBidirectionalNeighbor(central_w130);
        central_w135.addBidirectionalNeighbor(central_w136);
        central_w142.addBidirectionalNeighbor(central_w136);
        central_w136.addBidirectionalNeighbor(north_w39);
        north_w40.addBidirectionalNeighbor(north_w39);
        north_w39.addBidirectionalNeighbor(north_b9);
        north_w39.addBidirectionalNeighbor(north_w143);
        north_w143.addBidirectionalNeighbor(east_w144);
        east_w144.addBidirectionalNeighbor(central_w130);
        north_w143.addBidirectionalNeighbor(central_w130);
        east_w144.addBidirectionalNeighbor(east_w38);
        east_w37.addBidirectionalNeighbor(east_w38);
        east_w37.addBidirectionalNeighbor(east_w145);
        east_w37.addBidirectionalNeighbor(east_w33);
        east_w33.addBidirectionalNeighbor(east_w146);
        east_w146.addBidirectionalNeighbor(east_w147);
        east_w33.addBidirectionalNeighbor(east_w131);
        east_w32.addBidirectionalNeighbor(east_w33);
        east_w32.addBidirectionalNeighbor(east_w29);
        east_w29.addBidirectionalNeighbor(east_w30);
        east_w30.addBidirectionalNeighbor(east_w31);
        central_w124.addBidirectionalNeighbor(central_w123);
        east_w30.addBidirectionalNeighbor(central_b7);
        central_w35.addBidirectionalNeighbor(central_w150);
        central_w150.addBidirectionalNeighbor(central_w126);
        central_w150.addBidirectionalNeighbor(central_b7);
        central_b7.addBidirectionalNeighbor(central_w124);
        east_w122.addBidirectionalNeighbor(east_w31);
        east_w122.addBidirectionalNeighbor(east_w121);
        east_w28.addBidirectionalNeighbor(east_w29);
        east_w27.addBidirectionalNeighbor(east_w28);
        east_w26.addBidirectionalNeighbor(east_w27);
        east_w26.addBidirectionalNeighbor(east_w25);
        east_w24.addBidirectionalNeighbor(east_w25);
        east_w24.addBidirectionalNeighbor(east_w22);
        east_w22.addBidirectionalNeighbor(east_w23);
        east_w23.addBidirectionalNeighbor(east_b3);
        east_w151.addBidirectionalNeighbor(east_w26);
        east_w31.addBidirectionalNeighbor(east_b6);
        central_w120.addBidirectionalNeighbor(east_w121);
        central_w123.addBidirectionalNeighbor(central_w120);
        central_w152.addBidirectionalNeighbor(central_w120);
        central_w152.addBidirectionalNeighbor(central_b15);
        central_w152.addBidirectionalNeighbor(central_w119);
        central_w119.addBidirectionalNeighbor(central_w120);
        central_w119.addBidirectionalNeighbor(central_w117);
        central_w117.addBidirectionalNeighbor(central_b14);
        central_w119.addBidirectionalNeighbor(central_b14);
        central_w86.addBidirectionalNeighbor(central_b14);
        central_w85.addBidirectionalNeighbor(central_b15);
        central_w116.addBidirectionalNeighbor(central_w117);
        central_w117.addBidirectionalNeighbor(central_w118);
        central_w116.addBidirectionalNeighbor(central_w118);
        central_w5.addBidirectionalNeighbor(central_w116);
        central_w6.addBidirectionalNeighbor(central_w5);
        central_w119.addBidirectionalNeighbor(central_w153);
        east_w151.addBidirectionalNeighbor(central_w153);
        east_w154.addBidirectionalNeighbor(east_w151);
        east_w154.addBidirectionalNeighbor(east_b3);
        central_w118.addBidirectionalNeighbor(east_w154);
        east_w154.addBidirectionalNeighbor(east_w155);
        east_w24.addBidirectionalNeighbor(east_w155);
        east_w155.addBidirectionalNeighbor(east_w23);
        east_w22.addBidirectionalNeighbor(east_w9);
        south_w4.addBidirectionalNeighbor(central_w156);
        central_w156.addBidirectionalNeighbor(central_w5);
        central_w6.addBidirectionalNeighbor(central_w158);
        central_b13.addBidirectionalNeighbor(central_w158);
        central_w157.addBidirectionalNeighbor(central_w158);
        central_w158.addBidirectionalNeighbor(central_w117);
        central_w161.addBidirectionalNeighbor(central_w160);
        central_w161.addBidirectionalNeighbor(central_w162);
        central_w162.addBidirectionalNeighbor(central_w163);
        central_w163.addBidirectionalNeighbor(central_w97);
        central_w160.addBidirectionalNeighbor(central_w159);
        central_w159.addBidirectionalNeighbor(central_w156);
        central_w159.addBidirectionalNeighbor(central_w6);
        central_w88.addBidirectionalNeighbor(central_w166);
        central_w166.addBidirectionalNeighbor(central_w165);
        central_w165.addBidirectionalNeighbor(central_w164);
        central_w165.addBidirectionalNeighbor(central_w86);
        central_w164.addBidirectionalNeighbor(central_w157);
        central_w157.addBidirectionalNeighbor(central_w158);
        central_w167.addBidirectionalNeighbor(central_w116);
        central_w168.addBidirectionalNeighbor(central_w116);
        central_w168.addBidirectionalNeighbor(east_w154);
        south_w2.addBidirectionalNeighbor(south_w169);
        south_w169.addBidirectionalNeighbor(east_w170);
        east_w170.addBidirectionalNeighbor(east_w171);
        south_w4.addBidirectionalNeighbor(south_w177);
        south_w177.addBidirectionalNeighbor(south_w176);
        south_w176.addBidirectionalNeighbor(south_w178);
        south_w179.addBidirectionalNeighbor(south_w178);
        south_w179.addBidirectionalNeighbor(south_w177);
        south_w179.addBidirectionalNeighbor(south_w169);
        central_w167.addBidirectionalNeighbor(south_w176);
        south_w178.addBidirectionalNeighbor(east_w7);
        east_w171.addBidirectionalNeighbor(east_w172);
        east_w172.addBidirectionalNeighbor(east_w173);
        east_w173.addBidirectionalNeighbor(east_w174);
        east_w174.addBidirectionalNeighbor(east_w175);
        east_w174.addBidirectionalNeighbor(east_b18);
        east_w173.addBidirectionalNeighbor(east_w175);
        east_w9.addBidirectionalNeighbor(east_w180);
        east_w180.addBidirectionalNeighbor(east_w172);
        east_w172.addBidirectionalNeighbor(east_w7);
        east_w7.addBidirectionalNeighbor(east_w183);
        east_w183.addBidirectionalNeighbor(east_w8);
        east_w175.addBidirectionalNeighbor(east_w181);
        east_w181.addBidirectionalNeighbor(east_w180);
        east_w175.addBidirectionalNeighbor(east_w184);
        east_w184.addBidirectionalNeighbor(east_w185);
        east_w13.addBidirectionalNeighbor(east_w185);
        central_w192.addBidirectionalNeighbor(central_w67);
        central_w192.addBidirectionalNeighbor(west_b12);
        west_b12.addBidirectionalNeighbor(central_w191);
        west_b12.addBidirectionalNeighbor(west_w190);
        west_w189.addBidirectionalNeighbor(west_w190);
        west_w189.addBidirectionalNeighbor(central_w188);
        west_w190.addBidirectionalNeighbor(central_w191);
        central_w186.addBidirectionalNeighbor(central_w188);
        central_w186.addBidirectionalNeighbor(west_b11);
        west_w70.addBidirectionalNeighbor(west_w196);
        west_w68.addBidirectionalNeighbor(west_w196);
        west_w196.addBidirectionalNeighbor(west_w193);
        west_w193.addBidirectionalNeighbor(west_w194);
        west_w194.addBidirectionalNeighbor(west_b11);
        west_w189.addBidirectionalNeighbor(west_w197);
        west_w197.addBidirectionalNeighbor(west_w193);
        central_w186.addBidirectionalNeighbor(central_w187);
        central_w186.addBidirectionalNeighbor(central_w198);
        west_w199.addBidirectionalNeighbor(central_w198);
        west_w199.addBidirectionalNeighbor(west_w194);
        central_w187.addBidirectionalNeighbor(central_w76);
        north_w51.addBidirectionalNeighbor(north_w200);
        north_w200.addBidirectionalNeighbor(central_w50);
        north_w51.addBidirectionalNeighbor(north_w53);
        north_w51.addBidirectionalNeighbor(north_w55);
        north_w55.addBidirectionalNeighbor(north_w56);
        north_w56.addBidirectionalNeighbor(north_w57);
        north_w55.addBidirectionalNeighbor(north_w54);
        north_w54.addBidirectionalNeighbor(north_w53);
        north_w53.addBidirectionalNeighbor(north_w54);
        north_w48.addBidirectionalNeighbor(north_w54);
        north_w48.addBidirectionalNeighbor(north_w49);
        north_w49.addBidirectionalNeighbor(north_w57);
        north_w202.addBidirectionalNeighbor(north_w201);
        north_w201.addBidirectionalNeighbor(north_w48);
        north_w48.addBidirectionalNeighbor(east_w46);
        east_w46.addBidirectionalNeighbor(east_w45);
        east_w45.addBidirectionalNeighbor(east_w44);
        east_w44.addBidirectionalNeighbor(east_w43);
        east_w47.addBidirectionalNeighbor(east_w46);
        east_w47.addBidirectionalNeighbor(east_w38);
        north_w57.addBidirectionalNeighbor(north_w204);
        north_w48.addBidirectionalNeighbor(north_w203);
        east_w43.addBidirectionalNeighbor(east_w42);
        east_w41.addBidirectionalNeighbor(east_w42);
        east_w41.addBidirectionalNeighbor(east_g6);
        south_g4.addBidirectionalNeighbor(south_w1);
        south_w11.addBidirectionalNeighbor(south_w1);
        south_w2.addBidirectionalNeighbor(south_w1);
        east_w8.addBidirectionalNeighbor(east_w9);
        east_w9.addBidirectionalNeighbor(east_w10);
        east_w10.addBidirectionalNeighbor(east_w17);
        east_w17.addBidirectionalNeighbor(east_w16);
        east_w17.addBidirectionalNeighbor(east_w18);
        east_w18.addBidirectionalNeighbor(east_w19);
        east_w19.addBidirectionalNeighbor(east_w20);
        east_w20.addBidirectionalNeighbor(east_w21);
        east_w21.addBidirectionalNeighbor(east_w13);
        east_w13.addBidirectionalNeighbor(east_w14);
        east_w14.addBidirectionalNeighbor(east_w15);
        east_w13.addBidirectionalNeighbor(east_w12);
        east_g5.addBidirectionalNeighbor(east_w13);
        east_w15.addBidirectionalNeighbor(east_w16);
        east_w12.addBidirectionalNeighbor(south_w11);
        south_w4.addBidirectionalNeighbor(central_w99);
        central_w98.addBidirectionalNeighbor(central_w99);
        central_w98.addBidirectionalNeighbor(south_w104);
        south_w104.addBidirectionalNeighbor(west_w105);
        west_w105.addBidirectionalNeighbor(west_w106);
        west_w106.addBidirectionalNeighbor(west_w107);
        west_w107.addBidirectionalNeighbor(west_w108);
        west_w108.addBidirectionalNeighbor(west_w109);
        west_w113.addBidirectionalNeighbor(west_w109);
        west_w112.addBidirectionalNeighbor(west_w109);
        west_w113.addBidirectionalNeighbor(west_b16);
        west_w110.addBidirectionalNeighbor(west_w113);
        west_w110.addBidirectionalNeighbor(west_w111);
        west_w111.addBidirectionalNeighbor(west_w112);
        central_w98.addBidirectionalNeighbor(west_w92);
        central_w98.addBidirectionalNeighbor(central_w96);
        central_w96.addBidirectionalNeighbor(central_w97);
        central_w96.addBidirectionalNeighbor(central_w94);
        central_w94.addBidirectionalNeighbor(central_w93);
        central_w93.addBidirectionalNeighbor(central_w88);
        central_w88.addBidirectionalNeighbor(central_w89);
        central_w89.addBidirectionalNeighbor(central_w90);
        central_w90.addBidirectionalNeighbor(west_w91);
        west_w91.addBidirectionalNeighbor(west_w92);
        west_w92.addBidirectionalNeighbor(west_w100);
        west_w100.addBidirectionalNeighbor(west_w101);
        west_w101.addBidirectionalNeighbor(west_w102);
        west_w102.addBidirectionalNeighbor(west_w103);
        west_w103.addBidirectionalNeighbor(west_w71);
        west_w114.addBidirectionalNeighbor(west_w71);
        west_w114.addBidirectionalNeighbor(west_w70);
        central_w72.addBidirectionalNeighbor(west_w71);
        central_w72.addBidirectionalNeighbor(central_w73);
        central_w86.addBidirectionalNeighbor(central_w85);
        central_w85.addBidirectionalNeighbor(central_w86);
        central_w85.addBidirectionalNeighbor(central_w84);
        central_w73.addBidirectionalNeighbor(central_w74);
        central_w74.addBidirectionalNeighbor(central_w75);
        central_w75.addBidirectionalNeighbor(central_w76);
        central_w76.addBidirectionalNeighbor(central_w77);
        central_w75.addBidirectionalNeighbor(central_w78);
        central_w78.addBidirectionalNeighbor(central_w79);
        central_w79.addBidirectionalNeighbor(central_w77);
        central_w79.addBidirectionalNeighbor(central_w80);
        central_w80.addBidirectionalNeighbor(central_w81);
        central_w81.addBidirectionalNeighbor(central_w82);
        central_w82.addBidirectionalNeighbor(central_w83);
        central_w83.addBidirectionalNeighbor(central_w84);
        central_w36.addBidirectionalNeighbor(central_w80);
        west_w68.addBidirectionalNeighbor(west_w65);
        west_w68.addBidirectionalNeighbor(west_w69);
        west_w65.addBidirectionalNeighbor(west_w64);
        west_w65.addBidirectionalNeighbor(west_w66);
        west_w64.addBidirectionalNeighbor(west_w115);
        west_w115.addBidirectionalNeighbor(west_w63);
        west_w63.addBidirectionalNeighbor(west_w52);
        west_w52.addBidirectionalNeighbor(west_w62);
        west_w52.addBidirectionalNeighbor(west_w58);
        west_w52.addBidirectionalNeighbor(west_w59);
        west_w59.addBidirectionalNeighbor(west_w60);
        west_w59.addBidirectionalNeighbor(west_w61);
        west_w58.addBidirectionalNeighbor(north_w51);
        west_w148.addBidirectionalNeighbor(west_w58);
        central_w50.addBidirectionalNeighbor(north_w51);
        central_w50.addBidirectionalNeighbor(central_w67);
        west_w66.addBidirectionalNeighbor(central_w67);
        central_w50.addBidirectionalNeighbor(north_w40);
        north_w40.addBidirectionalNeighbor(central_w142);
        central_w139.addBidirectionalNeighbor(central_w142);
        central_w139.addBidirectionalNeighbor(central_w137);
        central_w139.addBidirectionalNeighbor(central_w140);
        central_w141.addBidirectionalNeighbor(central_w140);
        central_w36.addBidirectionalNeighbor(central_w140);
        central_w36.addBidirectionalNeighbor(central_w35);
        central_w35.addBidirectionalNeighbor(central_w126);
        central_w126.addBidirectionalNeighbor(central_w127);
        central_w127.addBidirectionalNeighbor(central_w128);
        central_w128.addBidirectionalNeighbor(central_w129);
        central_w129.addBidirectionalNeighbor(central_w134);
        central_w134.addBidirectionalNeighbor(central_w135);
        central_w135.addBidirectionalNeighbor(central_w137);
        central_w129.addBidirectionalNeighbor(east_w133);
        east_w132.addBidirectionalNeighbor(east_w133);
        east_w132.addBidirectionalNeighbor(east_w131);
        east_w131.addBidirectionalNeighbor(central_w126);
        east_w133.addBidirectionalNeighbor(central_w130);
        central_w129.addBidirectionalNeighbor(central_w130);
        central_w135.addBidirectionalNeighbor(central_w136);
        central_w142.addBidirectionalNeighbor(central_w136);
        central_w136.addBidirectionalNeighbor(north_w39);
        north_w40.addBidirectionalNeighbor(north_w39);
        north_w39.addBidirectionalNeighbor(north_b9);
        north_w39.addBidirectionalNeighbor(north_w143);
        north_w143.addBidirectionalNeighbor(east_w144);
        east_w144.addBidirectionalNeighbor(central_w130);
        north_w143.addBidirectionalNeighbor(central_w130);
        east_w144.addBidirectionalNeighbor(east_w38);
        east_w37.addBidirectionalNeighbor(east_w38);
        east_w37.addBidirectionalNeighbor(east_w145);
        east_w37.addBidirectionalNeighbor(east_w33);
        east_w33.addBidirectionalNeighbor(east_w146);
        east_w146.addBidirectionalNeighbor(east_w147);
        east_w33.addBidirectionalNeighbor(east_w131);
        east_w32.addBidirectionalNeighbor(east_w33);
        east_w32.addBidirectionalNeighbor(east_w29);
        east_w29.addBidirectionalNeighbor(east_w30);
        east_w30.addBidirectionalNeighbor(east_w31);
        central_w124.addBidirectionalNeighbor(central_w123);
        east_w30.addBidirectionalNeighbor(central_b7);
        central_w35.addBidirectionalNeighbor(central_w150);
        central_w150.addBidirectionalNeighbor(central_w126);
        central_w150.addBidirectionalNeighbor(central_b7);
        central_b7.addBidirectionalNeighbor(central_w124);
        east_w122.addBidirectionalNeighbor(east_w31);
        east_w122.addBidirectionalNeighbor(east_w121);
        east_w28.addBidirectionalNeighbor(east_w29);
        east_w27.addBidirectionalNeighbor(east_w28);
        east_w26.addBidirectionalNeighbor(east_w27);
        east_w26.addBidirectionalNeighbor(east_w25);
        east_w24.addBidirectionalNeighbor(east_w25);
        east_w24.addBidirectionalNeighbor(east_w22);
        east_w22.addBidirectionalNeighbor(east_w23);
        east_w23.addBidirectionalNeighbor(east_b3);
        east_w151.addBidirectionalNeighbor(east_w26);
        east_w31.addBidirectionalNeighbor(east_b6);
        central_w120.addBidirectionalNeighbor(east_w121);
        central_w123.addBidirectionalNeighbor(central_w120);
        central_w152.addBidirectionalNeighbor(central_w120);
        central_w152.addBidirectionalNeighbor(central_b15);
        central_w152.addBidirectionalNeighbor(central_w119);
        central_w119.addBidirectionalNeighbor(central_w120);
        central_w119.addBidirectionalNeighbor(central_w117);
        central_w117.addBidirectionalNeighbor(central_b14);
        central_w119.addBidirectionalNeighbor(central_b14);
        central_w86.addBidirectionalNeighbor(central_b14);
        central_w85.addBidirectionalNeighbor(central_b15);
        central_w116.addBidirectionalNeighbor(central_w117);
        central_w117.addBidirectionalNeighbor(central_w118);
        central_w116.addBidirectionalNeighbor(central_w118);
        central_w5.addBidirectionalNeighbor(central_w116);
        central_w6.addBidirectionalNeighbor(central_w5);
        central_w119.addBidirectionalNeighbor(central_w153);
        east_w151.addBidirectionalNeighbor(central_w153);
        east_w154.addBidirectionalNeighbor(east_w151);
        east_w154.addBidirectionalNeighbor(east_b3);
        central_w118.addBidirectionalNeighbor(east_w154);
        east_w154.addBidirectionalNeighbor(east_w155);
        east_w24.addBidirectionalNeighbor(east_w155);
        east_w155.addBidirectionalNeighbor(east_w23);
        east_w22.addBidirectionalNeighbor(east_w9);
        south_w4.addBidirectionalNeighbor(central_w156);
        central_w156.addBidirectionalNeighbor(central_w5);
        central_w6.addBidirectionalNeighbor(central_w158);
        central_b13.addBidirectionalNeighbor(central_w158);
        central_w157.addBidirectionalNeighbor(central_w158);
        central_w158.addBidirectionalNeighbor(central_w117);
        central_w161.addBidirectionalNeighbor(central_w160);
        central_w161.addBidirectionalNeighbor(central_w162);
        central_w162.addBidirectionalNeighbor(central_w163);
        central_w163.addBidirectionalNeighbor(central_w97);
        central_w160.addBidirectionalNeighbor(central_w159);
        central_w159.addBidirectionalNeighbor(central_w156);
        central_w159.addBidirectionalNeighbor(central_w6);
        central_w88.addBidirectionalNeighbor(central_w166);
        central_w166.addBidirectionalNeighbor(central_w165);
        central_w165.addBidirectionalNeighbor(central_w164);
        central_w165.addBidirectionalNeighbor(central_w86);
        central_w164.addBidirectionalNeighbor(central_w157);
        central_w157.addBidirectionalNeighbor(central_w158);
        central_w167.addBidirectionalNeighbor(central_w116);
        central_w168.addBidirectionalNeighbor(central_w116);
        central_w168.addBidirectionalNeighbor(east_w154);
        south_w2.addBidirectionalNeighbor(south_w169);
        south_w169.addBidirectionalNeighbor(east_w170);
        east_w170.addBidirectionalNeighbor(east_w171);
        south_w4.addBidirectionalNeighbor(south_w177);
        south_w177.addBidirectionalNeighbor(south_w176);
        south_w176.addBidirectionalNeighbor(south_w178);
        south_w179.addBidirectionalNeighbor(south_w178);
        south_w179.addBidirectionalNeighbor(south_w177);
        south_w179.addBidirectionalNeighbor(south_w169);
        central_w167.addBidirectionalNeighbor(south_w176);
        south_w178.addBidirectionalNeighbor(east_w7);
        east_w171.addBidirectionalNeighbor(east_w172);
        east_w172.addBidirectionalNeighbor(east_w173);
        east_w173.addBidirectionalNeighbor(east_w174);
        east_w174.addBidirectionalNeighbor(east_w175);
        east_w174.addBidirectionalNeighbor(east_b18);
        east_w173.addBidirectionalNeighbor(east_w175);
        east_w9.addBidirectionalNeighbor(east_w180);
        east_w180.addBidirectionalNeighbor(east_w172);
        east_w172.addBidirectionalNeighbor(east_w7);
        east_w7.addBidirectionalNeighbor(east_w183);
        east_w183.addBidirectionalNeighbor(east_w8);
        east_w175.addBidirectionalNeighbor(east_w181);
        east_w181.addBidirectionalNeighbor(east_w180);
        east_w175.addBidirectionalNeighbor(east_w184);
        east_w184.addBidirectionalNeighbor(east_w185);
        east_w13.addBidirectionalNeighbor(east_w185);
        central_w192.addBidirectionalNeighbor(central_w67);
        central_w192.addBidirectionalNeighbor(west_b12);
        west_b12.addBidirectionalNeighbor(central_w191);
        west_b12.addBidirectionalNeighbor(west_w190);
        west_w189.addBidirectionalNeighbor(west_w190);
        west_w189.addBidirectionalNeighbor(central_w188);
        west_w190.addBidirectionalNeighbor(central_w191);
        central_w186.addBidirectionalNeighbor(central_w188);
        central_w186.addBidirectionalNeighbor(west_b11);
        west_w70.addBidirectionalNeighbor(west_w196);
        west_w68.addBidirectionalNeighbor(west_w196);
        west_w196.addBidirectionalNeighbor(west_w193);
        west_w193.addBidirectionalNeighbor(west_w194);
        west_w194.addBidirectionalNeighbor(west_b11);
        west_w189.addBidirectionalNeighbor(west_w197);
        west_w197.addBidirectionalNeighbor(west_w193);
        central_w186.addBidirectionalNeighbor(central_w187);
        central_w186.addBidirectionalNeighbor(central_w198);
        west_w199.addBidirectionalNeighbor(central_w198);
        west_w199.addBidirectionalNeighbor(west_w194);
        central_w187.addBidirectionalNeighbor(central_w76);
        north_w51.addBidirectionalNeighbor(north_w200);
        north_w200.addBidirectionalNeighbor(central_w50);
        north_w51.addBidirectionalNeighbor(north_w53);
        north_w51.addBidirectionalNeighbor(north_w55);
        north_w55.addBidirectionalNeighbor(north_w56);
        north_w56.addBidirectionalNeighbor(north_w57);
        north_w55.addBidirectionalNeighbor(north_w54);
        north_w54.addBidirectionalNeighbor(north_w53);
        north_w53.addBidirectionalNeighbor(north_w54);
        north_w48.addBidirectionalNeighbor(north_w54);
        north_w48.addBidirectionalNeighbor(north_w49);
        north_w49.addBidirectionalNeighbor(north_w57);
        north_w202.addBidirectionalNeighbor(north_w201);
        north_w201.addBidirectionalNeighbor(north_w48);
        north_w48.addBidirectionalNeighbor(east_w46);
        east_w46.addBidirectionalNeighbor(east_w45);
        east_w45.addBidirectionalNeighbor(east_w44);
        east_w44.addBidirectionalNeighbor(east_w43);
        east_w47.addBidirectionalNeighbor(east_w46);
        east_w47.addBidirectionalNeighbor(east_w38);
        north_w57.addBidirectionalNeighbor(north_w204);
        north_w48.addBidirectionalNeighbor(north_w203);
        east_w43.addBidirectionalNeighbor(east_w42);
        east_w41.addBidirectionalNeighbor(east_w42);
        east_w41.addBidirectionalNeighbor(east_g6);
        east_w25.addBidirectionalNeighbor(east_w196);
        east_w196.addBidirectionalNeighbor(east_b4);
        east_w197.addBidirectionalNeighbor(east_b4);
        east_w198.addBidirectionalNeighbor(east_w32);
        east_w198.addBidirectionalNeighbor(east_w197);
        east_w198.addBidirectionalNeighbor(east_w196);


    }

    getBuildingGraph() {
        return this.buildingGraph;
    }

    getNode(nodeName) {
        return this.buildingGraph.get(nodeName);
    }
    
    getAllNodes() {
        return Array.from(this.buildingGraph.values());
    }
    
    getAllBuildings() {
        return Array.from(this.buildingGraph.values()).filter(node => node.type === 'building');
    }
    
    getAllWalkways() {
        return Array.from(this.buildingGraph.values()).filter(node => node.type === 'walkway');
    }
}

// Export for use in other modules
if (typeof module !== 'undefined' && module.exports) {
    module.exports = GraphDatabase;
}
